[package]
name = "csv-to-json"
version = "0.1.0"
authors = ["Thomas Thorburn"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
csv = "1"